server:
    port: 8080

spring:
  application:
    name: movie-backend

  servlet:
    multipart:
      max-file-size: 100MB      # 单个文件最大允许 100MB
      max-request-size: 500MB
  
  # 1. 数据库配置 (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 假设你用的是本地 MySQL，且已经建好了 movie_db 库
    url: jdbc:mysql://localhost:3306/movie_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 374629

  # 2. Redis 配置 (Docker)
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      timeout: 10000

  # 3. RabbitMQ 配置 (Docker)
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /

  # 4. Elasticsearch 配置 (Docker)
  elasticsearch:
    uris: http://localhost:9200
  
  # 5. Nacos 配置 (Docker)
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        file-extension: yaml
        import-check:
          enabled: false # 开发阶段先关掉强校验

# 6. MinIO 配置 (自定义配置)
minio:
  endpoint: http://localhost:9000
  accessKey: admin
  secretKey: password123
  bucketName: movie-media

# 7. MyBatis Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印SQL，方便调试
    map-underscore-to-camel-case: true # 开启下划线转驼峰
  global-config:
    db-config:
      logic-delete-field: isDeleted # 逻辑删除字段名
      logic-delete-value: 1
      logic-not-delete-value: 0